version: '3.8'
services:
  postgres:  # Postgres
    image: postgres:16-alpine  # Update version mới
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-tshop}
    volumes:
      - db-data:/var/lib/postgresql/data  # Persistent
    ports:
      - "5432:5432"  # Chỉ dev, bỏ ở prod
    networks:
      - tshop-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-tshop}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis-server:  # Redis
    image: redis:7-alpine
    volumes:
      - redis-data:/data  # Persistent
    ports:
      - "6379:6379"  # Chỉ dev
    networks:
      - tshop-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
  redis-data:

networks:
  tshop-net:
    driver: bridge