version: '3.8'
services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tshop
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tshop-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - tshop-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tshop.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - tshop-net

volumes:
  db-data:

networks:
  tshop-net:
    driver: bridge
